export const NAMES = [
  "PixelNinja",
  "CodeWizard",
  "Aarav_07",
  "StreamQueen",
  "devFromMumbai",
  "noobMaster69",
  "reactFanboy",
  "Priya.dev",
  "GG_Gamer",
  "lurker_99",
  "TechBro",
  "SaiTeja",
  "frontend_fox",
  "BetaTester",
  "Anonymous_User",
];

export const MESSAGES = [
  "🔥🔥🔥",
  "First!",
  "LET'S GOOO",
  "this is so cool",
  "W stream",
  "where you from?",
  "POG",
  "🐐🐐",
  "underrated fr",
  "❤️ from India",
  "can you do a tutorial on this?",
  "lol",
  "the editing is insane",
  "subscribed!",
  "GG",
  "facts",
  "who's here in 2026?",
  "🎉",
  "respect 🙏",
];
